"""Turn the live API keys into the two files the render server's front reads.

The site is the only place a key and its rights live. The render server reads a
TOML file for what each client may do; nginx reads a map to turn an API key into
a client name. This module renders both from the keys, as pure text, so the
command that writes them stays a thin shell over IO and the rendering is tested
without a filesystem.

Both renderings are sorted by client name, so the same keys yield byte-identical
files: rewriting one when nothing changed is a no-op, and a diff means the keys
moved.
"""

BANNER = (
    "# Generated by 'manage.py write_pdf_server_config' from the site's API "
    "keys.\n"
    "# Do not edit by hand: the next run overwrites it.\n"
)


def _toml_basic_string(value):
    """Return ``value`` as a quoted TOML basic string.

    Args:
        value: The string to quote.

    Returns:
        str: The value wrapped in double quotes, with the characters TOML
        requires escaping inside a basic string escaped.
    """
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _nginx_string(value):
    """Return ``value`` as a quoted nginx string.

    Args:
        value: The string to quote.

    Returns:
        str: The value in double quotes, backslash and quote escaped.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_clients_toml(keys, font_store_dir):
    """Return the ``clients.toml`` body granting each key what it may render.

    A key allowed fonts of its own is given a font directory named for its
    client under ``font_store_dir``; the server requires one whenever the right
    is granted, and creates it if it is missing.

    Args:
        keys: The live :class:`~api_keys.models.ApiKey` rows.
        font_store_dir: The parent path a client's own font directory hangs
            under.

    Returns:
        str: The file's full contents, banner included.
    """
    blocks = []
    for key in sorted(keys, key=lambda k: k.client_name):
        lines = [
            f"[clients.{key.client_name}]",
            f"allowed_to_use_its_own_fonts = "
            f"{str(key.allowed_to_use_its_own_fonts).lower()}",
        ]
        if key.max_pages is not None:
            lines.append(f"max_pages = {key.max_pages}")
        if key.allowed_to_use_its_own_fonts:
            font_dir = font_store_dir / key.client_name
            lines.append(f"font_dir = {_toml_basic_string(str(font_dir))}")
        blocks.append("\n".join(lines))
    body = "\n\n".join(blocks)
    return BANNER + ("\n" + body + "\n" if body else "")


def render_nginx_map(keys):
    """Return the nginx map turning an ``Authorization`` header into a client.

    An API key reaches nginx as a bearer token, so each key is matched with its
    ``Bearer`` prefix. A header the map does not carry falls to the empty
    string, which the front refuses.

    Args:
        keys: The live :class:`~api_keys.models.ApiKey` rows.

    Returns:
        str: The file's full contents, banner included.
    """
    lines = [
        "map $http_authorization $pdf_client {",
        '    default "";',
    ]
    for key in sorted(keys, key=lambda k: k.client_name):
        match = _nginx_string(f"Bearer {key.key}")
        lines.append(f"    {match} {key.client_name};")
    lines.append("}")
    return BANNER + "\n".join(lines) + "\n"
