# Generated by Django 6.0.7 on 2026-07-17 17:12

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import billing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_last_update", models.DateTimeField(auto_now=True)),
                (
                    "date_v_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("name", models.CharField(max_length=64, verbose_name="[plan name]")),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="[monthly price]"
                    ),
                ),
                (
                    "included_pages",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="[included pages]"
                    ),
                ),
                (
                    "included_requests",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="[included requests]"
                    ),
                ),
                (
                    "overage_page_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="[overage price per page]",
                    ),
                ),
                (
                    "overage_request_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="[overage price per request]",
                    ),
                ),
            ],
            options={
                "verbose_name": "[plan]",
                "verbose_name_plural": "[plans]",
                "ordering": ["date_v_start"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("date_v_end__isnull", True)),
                        fields=("name",),
                        name="uniq_plan_name_when_live",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_last_update", models.DateTimeField(auto_now=True)),
                (
                    "date_v_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("started_on", models.DateField(verbose_name="[started on]")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="[account]",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                        verbose_name="[plan]",
                    ),
                ),
            ],
            options={
                "verbose_name": "[subscription]",
                "verbose_name_plural": "[subscriptions]",
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_last_update", models.DateTimeField(auto_now=True)),
                (
                    "date_v_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("period_start", models.DateField(verbose_name="[period start]")),
                ("period_end", models.DateField(verbose_name="[period end]")),
                ("issued_on", models.DateField(verbose_name="[issued on]")),
                (
                    "currency",
                    models.CharField(
                        default=billing.models.default_currency,
                        max_length=3,
                        verbose_name="[currency]",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "[draft]"),
                            ("issued", "[issued]"),
                            ("paid", "[paid]"),
                            ("canceled", "[canceled]"),
                        ],
                        default="draft",
                        max_length=8,
                        verbose_name="[status]",
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="[monthly price]"
                    ),
                ),
                (
                    "included_pages",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="[included pages]"
                    ),
                ),
                (
                    "included_requests",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="[included requests]"
                    ),
                ),
                (
                    "overage_page_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="[overage price per page]",
                    ),
                ),
                (
                    "overage_request_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="[overage price per request]",
                    ),
                ),
                (
                    "used_pages",
                    models.PositiveIntegerField(default=0, verbose_name="[used pages]"),
                ),
                (
                    "used_requests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="[used requests]"
                    ),
                ),
                (
                    "overage_pages",
                    models.PositiveIntegerField(
                        default=0, verbose_name="[overage pages]"
                    ),
                ),
                (
                    "overage_requests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="[overage requests]"
                    ),
                ),
                (
                    "overage_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="[overage amount]",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="[total]",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="[account]",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="billing.subscription",
                        verbose_name="[subscription]",
                    ),
                ),
            ],
            options={
                "verbose_name": "[invoice]",
                "verbose_name_plural": "[invoices]",
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_last_update", models.DateTimeField(auto_now=True)),
                (
                    "date_v_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "client_name",
                    models.CharField(max_length=64, verbose_name="[client name]"),
                ),
                (
                    "event_id",
                    models.CharField(max_length=128, verbose_name="[event id]"),
                ),
                ("rendered_at", models.DateTimeField(verbose_name="[rendered at]")),
                ("pages", models.PositiveIntegerField(verbose_name="[pages]")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="[account]",
                    ),
                ),
            ],
            options={
                "verbose_name": "[usage record]",
                "verbose_name_plural": "[usage records]",
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date_v_end__isnull", True)),
                fields=("account",),
                name="uniq_subscription_account_when_live",
            ),
        ),
        migrations.AddConstraint(
            model_name="usagerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date_v_end__isnull", True)),
                fields=("event_id",),
                name="uniq_usage_event_id_when_live",
            ),
        ),
    ]
