# Generated by Django 6.0.7 on 2026-07-17 11:28

import django.utils.timezone
from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_last_update", models.DateTimeField(auto_now=True)),
                (
                    "date_v_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="[email address]"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="[full name]"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="[company]"
                    ),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="[VAT number]"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "[user]",
                "verbose_name_plural": "[users]",
                "ordering": ["date_v_start"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("date_v_end__isnull", True)),
                        fields=("email",),
                        name="uniq_user_email_when_live",
                    )
                ],
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
    ]
