# Generated by Django 6.0.7 on 2026-07-17 14:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import api_keys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_last_update", models.DateTimeField(auto_now=True)),
                (
                    "date_v_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "client_name",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[a-z0-9][a-z0-9_-]{0,63}\\Z",
                                "[A client name holds up to 64 lowercase letters, digits, underscores and dashes, and starts with a letter or a digit.]",
                            )
                        ],
                        verbose_name="[client name]",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=api_keys.models.generate_key,
                        max_length=64,
                        verbose_name="[key]",
                    ),
                ),
                (
                    "allowed_to_use_its_own_fonts",
                    models.BooleanField(
                        default=False, verbose_name="[allowed to use its own fonts]"
                    ),
                ),
                (
                    "max_pages",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="[max pages]"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="[account]",
                    ),
                ),
            ],
            options={
                "verbose_name": "[API key]",
                "verbose_name_plural": "[API keys]",
                "ordering": ["date_v_start"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("date_v_end__isnull", True)),
                        fields=("key",),
                        name="uniq_api_key_when_live",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("date_v_end__isnull", True)),
                        fields=("client_name",),
                        name="uniq_api_key_client_name_when_live",
                    ),
                ],
            },
        ),
    ]
